id: P78B8B084
initial_creation_type: input
source_metadata:
  title: Fifth Shamarpa
  language: bo
  description: 'Texts by and about the Fifth Shamarpa, Könchok Yenlak (dkon mchog
    yan lag, 1525–1583):'
  volume:
    84e9cb05f80b4584a37f46d881c2bab6:
      title: A Song of Calling the Guru from Afar
      parent: Prayers
created_at: '2022-02-28T23:15:32.571490'
last_modified_at: '2022-02-28T23:15:32.571492'
statistics:
  total_words: 768
  total_non_words: 54
quality:
  non_words_ratio: 0.07
